/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Actortype = "PLATFORM_ADMIN" | "USER";

export type Adjustmentreason = "CORRECTION" | "CYCLE_COUNT" | "DAMAGE" | "EXPIRY" | "OTHER" | "THEFT";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Goodsreceiptstatus = "DRAFT" | "POSTED" | "REVERSED";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Partytype = "BUSINESS" | "INDIVIDUAL";

export type Pricelisttype = "PURCHASE" | "SALES";

export type Productstatus = "ACTIVE" | "ARCHIVED" | "DISCONTINUED" | "DRAFT";

export type Producttype = "GOODS" | "SERVICE";

export type Purchaseorderstatus = "APPROVED" | "BILLED" | "CANCELLED" | "CLOSED" | "DRAFT" | "PARTIALLY_RECEIVED" | "RECEIVED" | "SENT" | "SUBMITTED";

export type Salesorderstatus = "ALLOCATED" | "CANCELLED" | "CLOSED" | "CONFIRMED" | "DRAFT" | "FULFILLED" | "INVOICED" | "ON_HOLD" | "PARTIALLY_FULFILLED";

export type Serialstatus = "IN_STOCK" | "RESERVED" | "RETURNED" | "SCRAPPED" | "SHIPPED";

export type Shipmentstatus = "CANCELLED" | "DELIVERED" | "PACKED" | "PENDING" | "PICKED" | "RETURNED" | "SHIPPED";

export type Stockmovementtype = "ADJUSTMENT_IN" | "ADJUSTMENT_OUT" | "OPENING_BALANCE" | "PRODUCTION_IN" | "PRODUCTION_OUT" | "PURCHASE_RECEIPT" | "PURCHASE_RETURN" | "SALES_ISSUE" | "SALES_RETURN" | "TRANSFER_IN" | "TRANSFER_OUT";

export type Supplierstatus = "ACTIVE" | "BLOCKED" | "INACTIVE" | "PENDING_APPROVAL";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Transferstatus = "CANCELLED" | "DRAFT" | "IN_TRANSIT" | "RECEIVED";

export type Userrole = "ACCOUNTANT" | "ADMIN" | "INVENTORY_MANAGER" | "PURCHASING_MANAGER" | "SALES_MANAGER" | "VIEWER" | "WAREHOUSE_OPERATOR";

export type Warehousetype = "QUARANTINE" | "RETURNS" | "STANDARD" | "TRANSIT" | "VIRTUAL";

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Address {
  city: string;
  country: string;
  createdAt: Generated<Timestamp>;
  customerId: Int8 | null;
  id: Generated<Int8>;
  isBilling: Generated<boolean>;
  isDefault: Generated<boolean>;
  isShipping: Generated<boolean>;
  label: string | null;
  line1: string;
  line2: string | null;
  postalCode: string;
  publicId: Generated<string>;
  state: string;
  supplierId: Int8 | null;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface AuditLog {
  action: string;
  actorId: Int8 | null;
  actorType: Generated<Actortype>;
  after: Json | null;
  before: Json | null;
  entityId: string;
  entityType: string;
  id: Generated<Int8>;
  occurredAt: Generated<Timestamp>;
  requestId: string | null;
  tenantId: Int8;
}

export interface BinLocation {
  code: string;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  tenantId: Int8;
  warehouseId: Int8;
}

export interface Brand {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
  publicId: Generated<string>;
  slug: string;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface Category {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
  parentId: Int8 | null;
  publicId: Generated<string>;
  slug: string;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface Customer {
  code: string;
  createdAt: Generated<Timestamp>;
  creditLimit: Numeric | null;
  currency: Generated<string>;
  displayName: string | null;
  email: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  legalName: string;
  partyType: Generated<Partytype>;
  paymentTerms: string | null;
  phone: string | null;
  publicId: Generated<string>;
  taxId: string | null;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface DocumentSequence {
  code: string;
  id: Generated<Int8>;
  nextNumber: Generated<number>;
  padding: Generated<number>;
  prefix: string;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface GoodsReceipt {
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  docNumber: string;
  id: Generated<Int8>;
  notes: string | null;
  poId: Int8;
  postedAt: Timestamp | null;
  postedById: Int8 | null;
  publicId: Generated<string>;
  receivedAt: Generated<Timestamp>;
  status: Generated<Goodsreceiptstatus>;
  supplierDeliveryNote: string | null;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
  warehouseId: Int8;
}

export interface GoodsReceiptLine {
  id: Generated<Int8>;
  lotId: Int8 | null;
  notes: string | null;
  poLineId: Int8;
  quantityReceived: Numeric;
  quantityRejected: Generated<Numeric>;
  receiptId: Int8;
  tenantId: Int8;
  unitCost: Numeric;
  variantId: Int8;
}

export interface PasswordResetToken {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<Int8>;
  token: string;
  usedAt: Timestamp | null;
  userId: Int8;
}

export interface PlatformAdmin {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
  publicId: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface PlatformAdminLoginToken {
  adminId: Int8;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<Int8>;
  tokenHash: string;
}

export interface PlatformAdminSession {
  adminId: Int8;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<Int8>;
  ipAddress: string | null;
  tokenHash: string;
}

export interface PlatformAuditLog {
  action: string;
  adminId: Int8 | null;
  after: Json | null;
  before: Json | null;
  id: Generated<Int8>;
  ipAddress: string | null;
  occurredAt: Generated<Timestamp>;
  requestId: string | null;
  targetId: string | null;
  targetType: string | null;
}

export interface PriceList {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isDefault: Generated<boolean>;
  name: string;
  publicId: Generated<string>;
  tenantId: Int8;
  type: Generated<Pricelisttype>;
  updatedAt: Generated<Timestamp>;
  validFrom: Timestamp | null;
  validTo: Timestamp | null;
}

export interface PriceListItem {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  minQty: Generated<Numeric>;
  priceListId: Int8;
  tenantId: Int8;
  unitPrice: Numeric;
  updatedAt: Generated<Timestamp>;
  variantId: Int8;
}

export interface Product {
  brandId: Int8 | null;
  categoryId: Int8;
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  description: string | null;
  hsnCode: string | null;
  id: Generated<Int8>;
  images: Generated<string[] | null>;
  isBatchTracked: Generated<boolean>;
  isSerialTracked: Generated<boolean>;
  isStockTracked: Generated<boolean>;
  name: string;
  publicId: Generated<string>;
  sku: string;
  slug: string;
  status: Generated<Productstatus>;
  tenantId: Int8;
  type: Generated<Producttype>;
  uomId: Int8;
  updatedAt: Generated<Timestamp>;
  weight: Numeric | null;
  weightUom: string | null;
}

export interface ProductAttribute {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  tenantId: Int8;
}

export interface ProductAttributeValue {
  attributeId: Int8;
  id: Generated<Int8>;
  sortOrder: Generated<number>;
  tenantId: Int8;
  value: string;
}

export interface ProductSupplier {
  cost: Numeric;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isPrimary: Generated<boolean>;
  leadTimeDays: Generated<number>;
  minOrderQty: Generated<Numeric>;
  productId: Int8;
  supplierId: Int8;
  supplierSku: string | null;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface ProductVariant {
  barcode: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  listPrice: Numeric;
  name: string | null;
  productId: Int8;
  publicId: Generated<string>;
  sku: string;
  standardCost: Numeric | null;
  tenantId: Int8;
  uomId: Int8;
  updatedAt: Generated<Timestamp>;
  weight: Numeric | null;
  weightUom: string | null;
}

export interface ProductVariantAttribute {
  attributeValueId: Int8;
  variantId: Int8;
}

export interface PurchaseOrder {
  approvedAt: Timestamp | null;
  approvedById: Int8 | null;
  closedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  currency: Generated<string>;
  docNumber: string;
  expectedDate: Timestamp | null;
  grandTotal: Generated<Numeric>;
  id: Generated<Int8>;
  notes: string | null;
  orderDate: Generated<Timestamp>;
  publicId: Generated<string>;
  sentAt: Timestamp | null;
  shippingTotal: Generated<Numeric>;
  status: Generated<Purchaseorderstatus>;
  subtotal: Generated<Numeric>;
  supplierId: Int8;
  supplierRef: string | null;
  taxTotal: Generated<Numeric>;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
  warehouseId: Int8;
}

export interface PurchaseOrderLine {
  description: string | null;
  discountPct: Generated<Numeric>;
  expectedDate: Timestamp | null;
  id: Generated<Int8>;
  lineNumber: number;
  lineSubtotal: Numeric;
  lineTax: Generated<Numeric>;
  lineTotal: Numeric;
  poId: Int8;
  quantityCancelled: Generated<Numeric>;
  quantityOrdered: Numeric;
  quantityReceived: Generated<Numeric>;
  taxRate: Generated<Numeric>;
  tenantId: Int8;
  unitCost: Numeric;
  variantId: Int8;
}

export interface SalesOrder {
  billingAddress: Json | null;
  cancelledAt: Timestamp | null;
  closedAt: Timestamp | null;
  confirmedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  currency: Generated<string>;
  customerId: Int8;
  customerRef: string | null;
  discountTotal: Generated<Numeric>;
  docNumber: string;
  grandTotal: Generated<Numeric>;
  id: Generated<Int8>;
  notes: string | null;
  orderDate: Generated<Timestamp>;
  publicId: Generated<string>;
  requestedDate: Timestamp | null;
  shippingAddress: Json | null;
  shippingTotal: Generated<Numeric>;
  status: Generated<Salesorderstatus>;
  subtotal: Generated<Numeric>;
  taxTotal: Generated<Numeric>;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
  warehouseId: Int8;
}

export interface SalesOrderLine {
  description: string | null;
  discountPct: Generated<Numeric>;
  id: Generated<Int8>;
  lineNumber: number;
  lineSubtotal: Numeric;
  lineTax: Generated<Numeric>;
  lineTotal: Numeric;
  quantityCancelled: Generated<Numeric>;
  quantityOrdered: Numeric;
  quantityShipped: Generated<Numeric>;
  soId: Int8;
  taxRate: Generated<Numeric>;
  tenantId: Int8;
  unitPrice: Numeric;
  variantId: Int8;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<Int8>;
  token: string;
  userId: Int8;
}

export interface Shipment {
  carrier: string | null;
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  deliveredAt: Timestamp | null;
  docNumber: string;
  id: Generated<Int8>;
  notes: string | null;
  postedAt: Timestamp | null;
  postedById: Int8 | null;
  publicId: Generated<string>;
  shippedAt: Timestamp | null;
  soId: Int8;
  status: Generated<Shipmentstatus>;
  tenantId: Int8;
  trackingNumber: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ShipmentLine {
  id: Generated<Int8>;
  lotId: Int8 | null;
  quantityShipped: Numeric;
  shipmentId: Int8;
  soLineId: Int8;
  tenantId: Int8;
}

export interface StockAdjustment {
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  docNumber: string;
  id: Generated<Int8>;
  notes: string | null;
  postedAt: Timestamp | null;
  publicId: Generated<string>;
  reason: Adjustmentreason;
  tenantId: Int8;
  warehouseId: Int8;
}

export interface StockAdjustmentLine {
  adjustmentId: Int8;
  id: Generated<Int8>;
  lotId: Int8 | null;
  notes: string | null;
  quantity: Numeric;
  tenantId: Int8;
  unitCost: Numeric | null;
  variantId: Int8;
}

export interface StockLevel {
  id: Generated<Int8>;
  incoming: Generated<Numeric>;
  maxStockLevel: Numeric | null;
  onHand: Generated<Numeric>;
  reorderPoint: Numeric | null;
  reorderQty: Numeric | null;
  reserved: Generated<Numeric>;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
  variantId: Int8;
  warehouseId: Int8;
}

export interface StockLot {
  expiryDate: Timestamp | null;
  id: Generated<Int8>;
  lotNumber: string;
  manufacturedAt: Timestamp | null;
  notes: string | null;
  receivedAt: Generated<Timestamp>;
  tenantId: Int8;
  variantId: Int8;
}

export interface StockMovement {
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  id: Generated<Int8>;
  lotId: Int8 | null;
  notes: string | null;
  occurredAt: Generated<Timestamp>;
  publicId: Generated<string>;
  quantity: Numeric;
  sourceAdjustmentLineId: Int8 | null;
  sourceGoodsReceiptLineId: Int8 | null;
  sourceShipmentLineId: Int8 | null;
  sourceTransferLineId: Int8 | null;
  tenantId: Int8;
  type: Stockmovementtype;
  unitCost: Numeric | null;
  variantId: Int8;
  warehouseId: Int8;
}

export interface StockReservation {
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  expiresAt: Timestamp | null;
  id: Generated<Int8>;
  quantity: Numeric;
  salesOrderLineId: Int8 | null;
  tenantId: Int8;
  variantId: Int8;
  warehouseId: Int8;
}

export interface StockSerial {
  createdAt: Generated<Timestamp>;
  goodsReceiptLineId: Int8 | null;
  id: Generated<Int8>;
  lotId: Int8 | null;
  notes: string | null;
  publicId: Generated<string>;
  serialNumber: string;
  shipmentLineId: Int8 | null;
  status: Generated<Serialstatus>;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
  variantId: Int8;
  warehouseId: Int8 | null;
}

export interface StockTransfer {
  createdAt: Generated<Timestamp>;
  createdById: Int8 | null;
  docNumber: string;
  fromWarehouseId: Int8;
  id: Generated<Int8>;
  notes: string | null;
  publicId: Generated<string>;
  receivedAt: Timestamp | null;
  shippedAt: Timestamp | null;
  status: Generated<Transferstatus>;
  tenantId: Int8;
  toWarehouseId: Int8;
}

export interface StockTransferLine {
  id: Generated<Int8>;
  lotId: Int8 | null;
  quantityReceived: Generated<Numeric>;
  quantityShipped: Numeric;
  tenantId: Int8;
  transferId: Int8;
  variantId: Int8;
}

export interface Supplier {
  code: string;
  createdAt: Generated<Timestamp>;
  creditLimit: Numeric | null;
  currency: Generated<string>;
  displayName: string | null;
  email: string | null;
  id: Generated<Int8>;
  legalName: string;
  notes: string | null;
  pan: string | null;
  partyType: Generated<Partytype>;
  paymentTerms: string | null;
  phone: string | null;
  publicId: Generated<string>;
  status: Generated<Supplierstatus>;
  taxId: string | null;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
  website: string | null;
}

export interface SupplierContact {
  createdAt: Generated<Timestamp>;
  designation: string | null;
  email: string | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  isPrimary: Generated<boolean>;
  name: string;
  phone: string | null;
  supplierId: Int8;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface Tenant {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
  plan: Generated<string>;
  publicId: Generated<string>;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface UnitOfMeasure {
  baseUnitCode: string | null;
  category: string;
  code: string;
  conversion: Numeric | null;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
  password: string;
  phone: string | null;
  publicId: Generated<string>;
  role: Generated<Userrole>;
  tenantId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface Warehouse {
  addressLine1: string | null;
  addressLine2: string | null;
  allowsNegative: Generated<boolean>;
  city: string | null;
  code: string;
  country: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  isActive: Generated<boolean>;
  name: string;
  postalCode: string | null;
  publicId: Generated<string>;
  state: string | null;
  tenantId: Int8;
  type: Generated<Warehousetype>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  Address: Address;
  AuditLog: AuditLog;
  BinLocation: BinLocation;
  Brand: Brand;
  Category: Category;
  Customer: Customer;
  DocumentSequence: DocumentSequence;
  GoodsReceipt: GoodsReceipt;
  GoodsReceiptLine: GoodsReceiptLine;
  PasswordResetToken: PasswordResetToken;
  PlatformAdmin: PlatformAdmin;
  PlatformAdminLoginToken: PlatformAdminLoginToken;
  PlatformAdminSession: PlatformAdminSession;
  PlatformAuditLog: PlatformAuditLog;
  PriceList: PriceList;
  PriceListItem: PriceListItem;
  Product: Product;
  ProductAttribute: ProductAttribute;
  ProductAttributeValue: ProductAttributeValue;
  ProductSupplier: ProductSupplier;
  ProductVariant: ProductVariant;
  ProductVariantAttribute: ProductVariantAttribute;
  PurchaseOrder: PurchaseOrder;
  PurchaseOrderLine: PurchaseOrderLine;
  SalesOrder: SalesOrder;
  SalesOrderLine: SalesOrderLine;
  Session: Session;
  Shipment: Shipment;
  ShipmentLine: ShipmentLine;
  StockAdjustment: StockAdjustment;
  StockAdjustmentLine: StockAdjustmentLine;
  StockLevel: StockLevel;
  StockLot: StockLot;
  StockMovement: StockMovement;
  StockReservation: StockReservation;
  StockSerial: StockSerial;
  StockTransfer: StockTransfer;
  StockTransferLine: StockTransferLine;
  Supplier: Supplier;
  SupplierContact: SupplierContact;
  Tenant: Tenant;
  UnitOfMeasure: UnitOfMeasure;
  User: User;
  Warehouse: Warehouse;
}
